[build]
  base = "/"
  publish = "/out"
  command = "next build && next export"
  functions = "functions/"
  
[[ redirects ]]
  from = "https://sunnygolovinedotcom.netlify.app"
  to = "https://sunnygolovine.com"
  status = 301
  force = true