[build]
  base = "/"
  publish = "/out"
  command = "next build && next export"
  functions = "functions/"

[context.deploy-preview.enviroment]
  NODE_ENV = 'production'

[context.production.enviorment]
  NODE_ENV = 'production'

[context.branch-deploy.enviorment]
  NODE_ENV = 'production'
  
[[ redirects ]]
  from = "https://sunnygolovinedotcom.netlify.app"
  to = "https://sunnygolovine.com"
  status = 301
  force = true